2020-03-05 11:23:48,549 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/root/dpython/lib/python3.7/site-packages/rasa/nlu/registry.py", line 141, in get_component_class
    return class_from_module_path(component_name)
  File "/root/dpython/lib/python3.7/site-packages/rasa/utils/common.py", line 188, in class_from_module_path
    m = importlib.import_module(module_name)
  File "/root/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa.nlu.featurizers.sparse_featurizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dpython/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/root/dpython/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/root/dpython/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/root/dpython/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/root/dpython/lib/python3.7/site-packages/rasa/core/agent.py", line 233, in load_agent
    remote_storage=remote_storage,
  File "/root/dpython/lib/python3.7/site-packages/rasa/core/agent.py", line 878, in load_local_model
    remote_storage=remote_storage,
  File "/root/dpython/lib/python3.7/site-packages/rasa/core/agent.py", line 364, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "/root/dpython/lib/python3.7/site-packages/rasa/core/interpreter.py", line 45, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/root/dpython/lib/python3.7/site-packages/rasa/core/interpreter.py", line 246, in __init__
    self._load_interpreter()
  File "/root/dpython/lib/python3.7/site-packages/rasa/core/interpreter.py", line 264, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/root/dpython/lib/python3.7/site-packages/rasa/nlu/model.py", line 302, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/root/dpython/lib/python3.7/site-packages/rasa/nlu/model.py", line 324, in create
    components.validate_requirements(model_metadata.component_classes)
  File "/root/dpython/lib/python3.7/site-packages/rasa/nlu/components.py", line 36, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/root/dpython/lib/python3.7/site-packages/rasa/nlu/registry.py", line 150, in get_component_class
    "in a module.".format(component_name)
Exception: Failed to find component class for 'rasa.nlu.featurizers.sparse_featurizer.regex_featurizer.RegexFeaturizer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
